[package]
name = "day_3_manhattan_distance"
version = "0.1.0"
authors = ["Jeremy Sylvis <jeremy.sylvis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.19"